// 价格源未收录新模型时的内置兜底价（$/token），定价源命中同名条目时不生效
// DEC_20261001_114137 内置兜底 + 种子同步；Claude 价对齐 Claude Code 2.1.280 pricing_tiers，
// GPT-6 Sol/Luna 对齐 sub2api resources（2026-09-22 官方价）；>272K 档按输入 2x / 输出 1.5x
// 下线条件：远程定价源稳定包含同名条目且金额一致后删除对应条目

const CLAUDE_SHARED_META = {
  litellm_provider: 'anthropic',
  max_input_tokens: 1000000,
  max_output_tokens: 128000,
  max_tokens: 128000,
  mode: 'chat',
  search_context_cost_per_query: {
    search_context_size_high: 0.01,
    search_context_size_low: 0.01,
    search_context_size_medium: 0.01,
  },
  supports_adaptive_thinking: true,
  supports_assistant_prefill: false,
  supports_computer_use: true,
  supports_function_calling: true,
  supports_max_reasoning_effort: true,
  supports_output_config: true,
  supports_pdf_input: true,
  supports_prompt_caching: true,
  supports_reasoning: true,
  supports_response_schema: true,
  supports_tool_choice: true,
  supports_vision: true,
  supports_xhigh_reasoning_effort: true,
}

const GPT6_SHARED_META = {
  litellm_provider: 'openai',
  max_input_tokens: 872000,
  max_output_tokens: 128000,
  max_tokens: 128000,
  mode: 'chat',
  supported_endpoints: ['/v1/chat/completions', '/v1/batch', '/v1/responses'],
  supported_modalities: ['text', 'image'],
  supported_output_modalities: ['text'],
  supports_function_calling: true,
  supports_minimal_reasoning_effort: false,
  supports_native_streaming: true,
  supports_parallel_function_calling: true,
  supports_pdf_input: true,
  supports_prompt_caching: true,
  supports_reasoning: true,
  supports_response_schema: true,
  supports_service_tier: true,
  supports_system_messages: true,
  supports_tool_choice: true,
  supports_vision: true,
  supports_web_search: true,
  supports_xhigh_reasoning_effort: true,
}

export const MODEL_FALLBACK_PRICING = {
  // Claude Code 2.1.280 tier_4_20_cache_read_0_20；fast 2x 对齐 sub2api
  'claude-opus-5-5': {
    ...CLAUDE_SHARED_META,
    input_cost_per_token: 4e-6,
    output_cost_per_token: 2e-5,
    cache_creation_input_token_cost: 5e-6,
    cache_creation_input_token_cost_above_1hr: 8e-6,
    cache_read_input_token_cost: 2e-7,
    provider_specific_entry: { fast: 2.0 },
  },
  // sub2api resources（platform.claude.com sonnet-5-5 overview）
  'claude-sonnet-5-5': {
    ...CLAUDE_SHARED_META,
    input_cost_per_token: 2e-6,
    output_cost_per_token: 1e-5,
    cache_creation_input_token_cost: 2.5e-6,
    cache_creation_input_token_cost_above_1hr: 4e-6,
    cache_read_input_token_cost: 2e-7,
  },
  // GPT-6 Sol / Luna：sub2api resources 2026-09-22 官方价
  'gpt-6.1-sol': {
    ...GPT6_SHARED_META,
    input_cost_per_token: 2e-6,
    input_cost_per_token_above_272k_tokens: 4e-6,
    input_cost_per_token_above_272k_tokens_flex: 2e-6,
    input_cost_per_token_above_272k_tokens_priority: 8e-6,
    input_cost_per_token_batches: 1e-6,
    input_cost_per_token_flex: 1e-6,
    input_cost_per_token_priority: 4e-6,
    output_cost_per_token: 1e-5,
    output_cost_per_token_above_272k_tokens: 1.5e-5,
    output_cost_per_token_above_272k_tokens_flex: 7.5e-6,
    output_cost_per_token_above_272k_tokens_priority: 3e-5,
    output_cost_per_token_batches: 5e-6,
    output_cost_per_token_flex: 5e-6,
    output_cost_per_token_priority: 2e-5,
    cache_creation_input_token_cost: 2.5e-6,
    cache_creation_input_token_cost_above_272k_tokens: 5e-6,
    cache_creation_input_token_cost_above_272k_tokens_flex: 2.5e-6,
    cache_creation_input_token_cost_above_272k_tokens_priority: 1e-5,
    cache_creation_input_token_cost_batches: 1.25e-6,
    cache_creation_input_token_cost_flex: 1.25e-6,
    cache_creation_input_token_cost_priority: 5e-6,
    cache_read_input_token_cost: 1e-7,
    cache_read_input_token_cost_above_272k_tokens: 2e-7,
    cache_read_input_token_cost_above_272k_tokens_flex: 1e-7,
    cache_read_input_token_cost_above_272k_tokens_priority: 4e-7,
    cache_read_input_token_cost_batches: 5e-8,
    cache_read_input_token_cost_flex: 5e-8,
    cache_read_input_token_cost_priority: 2e-7,
    supports_none_reasoning_effort: false,
  },
  'gpt-6-sol': {
    ...GPT6_SHARED_META,
    input_cost_per_token: 2e-6,
    input_cost_per_token_above_272k_tokens: 4e-6,
    input_cost_per_token_above_272k_tokens_flex: 2e-6,
    input_cost_per_token_above_272k_tokens_priority: 8e-6,
    input_cost_per_token_batches: 1e-6,
    input_cost_per_token_flex: 1e-6,
    input_cost_per_token_priority: 4e-6,
    output_cost_per_token: 1e-5,
    output_cost_per_token_above_272k_tokens: 1.5e-5,
    output_cost_per_token_above_272k_tokens_flex: 7.5e-6,
    output_cost_per_token_above_272k_tokens_priority: 3e-5,
    output_cost_per_token_batches: 5e-6,
    output_cost_per_token_flex: 5e-6,
    output_cost_per_token_priority: 2e-5,
    cache_creation_input_token_cost: 2.5e-6,
    cache_creation_input_token_cost_above_272k_tokens: 5e-6,
    cache_creation_input_token_cost_above_272k_tokens_flex: 2.5e-6,
    cache_creation_input_token_cost_above_272k_tokens_priority: 1e-5,
    cache_creation_input_token_cost_batches: 1.25e-6,
    cache_creation_input_token_cost_flex: 1.25e-6,
    cache_creation_input_token_cost_priority: 5e-6,
    cache_read_input_token_cost: 2e-7,
    cache_read_input_token_cost_above_272k_tokens: 4e-7,
    cache_read_input_token_cost_above_272k_tokens_flex: 2e-7,
    cache_read_input_token_cost_above_272k_tokens_priority: 8e-7,
    cache_read_input_token_cost_batches: 1e-7,
    cache_read_input_token_cost_flex: 1e-7,
    cache_read_input_token_cost_priority: 4e-7,
    supports_none_reasoning_effort: true,
  },
  'gpt-6-luna': {
    ...GPT6_SHARED_META,
    input_cost_per_token: 1e-7,
    input_cost_per_token_above_272k_tokens: 2e-7,
    input_cost_per_token_above_272k_tokens_flex: 1e-7,
    input_cost_per_token_above_272k_tokens_priority: 4e-7,
    input_cost_per_token_batches: 5e-8,
    input_cost_per_token_flex: 5e-8,
    input_cost_per_token_priority: 2e-7,
    output_cost_per_token: 5e-7,
    output_cost_per_token_above_272k_tokens: 7.5e-7,
    output_cost_per_token_above_272k_tokens_flex: 3.75e-7,
    output_cost_per_token_above_272k_tokens_priority: 1.5e-6,
    output_cost_per_token_batches: 2.5e-7,
    output_cost_per_token_flex: 2.5e-7,
    output_cost_per_token_priority: 1e-6,
    cache_creation_input_token_cost: 1.25e-7,
    cache_creation_input_token_cost_above_272k_tokens: 2.5e-7,
    cache_creation_input_token_cost_above_272k_tokens_flex: 1.25e-7,
    cache_creation_input_token_cost_above_272k_tokens_priority: 5e-7,
    cache_creation_input_token_cost_batches: 6.25e-8,
    cache_creation_input_token_cost_flex: 6.25e-8,
    cache_creation_input_token_cost_priority: 2.5e-7,
    cache_read_input_token_cost: 1e-8,
    cache_read_input_token_cost_above_272k_tokens: 2e-8,
    cache_read_input_token_cost_above_272k_tokens_flex: 1e-8,
    cache_read_input_token_cost_above_272k_tokens_priority: 4e-8,
    cache_read_input_token_cost_batches: 5e-9,
    cache_read_input_token_cost_flex: 5e-9,
    cache_read_input_token_cost_priority: 2e-8,
    supports_none_reasoning_effort: true,
  },
}

// Bedrock / 区域前缀 ID 归一后查兜底
export const resolveModelFallbackPricing = (modelName) => {
  if (typeof modelName !== 'string' || !modelName) {
    return null
  }
  const normalized = modelName
    .toLowerCase()
    .replace(/\[1m\]$/, '')
    .replace(/^(us|eu|apac|global)\./, '')
    .replace(/^anthropic\./, '')
  return MODEL_FALLBACK_PRICING[normalized] || null
}
