// gpt-5.6 系列官方价兜底（LiteLLM/镜像未收录或过期时用）
// 来源：与 llysc model_prices 对齐的 OpenAI 官方公开价（$/token）
// sol/base: $5/$30 per M；terra: $2/$12；luna: $0.2/$1.2；均含 Priority/Flex/>272K
// 下线条件：远程定价源稳定包含同名字段且金额一致后可删

export const GPT56_SERIES_FALLBACK_PRICING = {
  'gpt-5.6': {
    cache_creation_input_token_cost: 0.00000625,
    cache_creation_input_token_cost_above_272k_tokens: 0.0000125,
    cache_creation_input_token_cost_above_272k_tokens_flex: 0.00000625,
    cache_creation_input_token_cost_flex: 0.000003125,
    cache_creation_input_token_cost_priority: 0.0000125,
    cache_read_input_token_cost: 5e-7,
    cache_read_input_token_cost_above_272k_tokens: 0.000001,
    cache_read_input_token_cost_above_272k_tokens_flex: 5e-7,
    cache_read_input_token_cost_flex: 2.5e-7,
    cache_read_input_token_cost_priority: 0.000001,
    input_cost_per_token: 0.000005,
    input_cost_per_token_above_272k_tokens: 0.00001,
    input_cost_per_token_above_272k_tokens_flex: 0.000005,
    input_cost_per_token_batches: 0.0000025,
    input_cost_per_token_flex: 0.0000025,
    input_cost_per_token_priority: 0.00001,
    litellm_provider: 'openai',
    max_input_tokens: 1050000,
    max_output_tokens: 128000,
    max_tokens: 128000,
    mode: 'chat',
    output_cost_per_token: 0.00003,
    output_cost_per_token_above_272k_tokens: 0.000045,
    output_cost_per_token_above_272k_tokens_flex: 0.0000225,
    output_cost_per_token_batches: 0.000015,
    output_cost_per_token_flex: 0.000015,
    output_cost_per_token_priority: 0.00006,
    regional_processing_uplift_multiplier_eu: 1.1,
    regional_processing_uplift_multiplier_us: 1.1,
    search_context_cost_per_query: {
      search_context_size_high: 0.01,
      search_context_size_low: 0.01,
      search_context_size_medium: 0.01,
    },
    supported_endpoints: ['/v1/chat/completions', '/v1/batch', '/v1/responses'],
    supported_modalities: ['text', 'image'],
    supported_output_modalities: ['text'],
    supports_function_calling: true,
    supports_minimal_reasoning_effort: false,
    supports_native_streaming: true,
    supports_none_reasoning_effort: true,
    supports_parallel_function_calling: true,
    supports_pdf_input: true,
    supports_prompt_caching: true,
    supports_reasoning: true,
    supports_response_schema: true,
    supports_system_messages: true,
    supports_tool_choice: true,
    supports_vision: true,
    supports_web_search: true,
    supports_xhigh_reasoning_effort: true,
    cache_read_input_token_cost_above_272k_tokens_priority: 0.000002,
    input_cost_per_token_above_272k_tokens_priority: 0.00002,
    output_cost_per_token_above_272k_tokens_priority: 0.00009,
    supports_service_tier: true,
  },
  'gpt-5.6-sol': {
    cache_creation_input_token_cost: 0.00000625,
    cache_creation_input_token_cost_above_272k_tokens: 0.0000125,
    cache_creation_input_token_cost_above_272k_tokens_flex: 0.00000625,
    cache_creation_input_token_cost_flex: 0.000003125,
    cache_creation_input_token_cost_priority: 0.0000125,
    cache_read_input_token_cost: 5e-7,
    cache_read_input_token_cost_above_272k_tokens: 0.000001,
    cache_read_input_token_cost_above_272k_tokens_flex: 5e-7,
    cache_read_input_token_cost_flex: 2.5e-7,
    cache_read_input_token_cost_priority: 0.000001,
    input_cost_per_token: 0.000005,
    input_cost_per_token_above_272k_tokens: 0.00001,
    input_cost_per_token_above_272k_tokens_flex: 0.000005,
    input_cost_per_token_batches: 0.0000025,
    input_cost_per_token_flex: 0.0000025,
    input_cost_per_token_priority: 0.00001,
    litellm_provider: 'openai',
    max_input_tokens: 1050000,
    max_output_tokens: 128000,
    max_tokens: 128000,
    mode: 'chat',
    output_cost_per_token: 0.00003,
    output_cost_per_token_above_272k_tokens: 0.000045,
    output_cost_per_token_above_272k_tokens_flex: 0.0000225,
    output_cost_per_token_batches: 0.000015,
    output_cost_per_token_flex: 0.000015,
    output_cost_per_token_priority: 0.00006,
    regional_processing_uplift_multiplier_eu: 1.1,
    regional_processing_uplift_multiplier_us: 1.1,
    search_context_cost_per_query: {
      search_context_size_high: 0.01,
      search_context_size_low: 0.01,
      search_context_size_medium: 0.01,
    },
    supported_endpoints: ['/v1/chat/completions', '/v1/batch', '/v1/responses'],
    supported_modalities: ['text', 'image'],
    supported_output_modalities: ['text'],
    supports_function_calling: true,
    supports_minimal_reasoning_effort: false,
    supports_native_streaming: true,
    supports_none_reasoning_effort: true,
    supports_parallel_function_calling: true,
    supports_pdf_input: true,
    supports_prompt_caching: true,
    supports_reasoning: true,
    supports_response_schema: true,
    supports_system_messages: true,
    supports_tool_choice: true,
    supports_vision: true,
    supports_web_search: true,
    supports_xhigh_reasoning_effort: true,
    cache_read_input_token_cost_above_272k_tokens_priority: 0.000002,
    input_cost_per_token_above_272k_tokens_priority: 0.00002,
    output_cost_per_token_above_272k_tokens_priority: 0.00009,
    supports_service_tier: true,
  },
  'gpt-5.6-terra': {
    cache_creation_input_token_cost: 0.0000025,
    cache_creation_input_token_cost_above_272k_tokens: 0.000005,
    cache_creation_input_token_cost_above_272k_tokens_flex: 0.0000025,
    cache_creation_input_token_cost_flex: 0.00000125,
    cache_creation_input_token_cost_priority: 0.000005,
    cache_read_input_token_cost: 2e-7,
    cache_read_input_token_cost_above_272k_tokens: 4e-7,
    cache_read_input_token_cost_above_272k_tokens_flex: 2e-7,
    cache_read_input_token_cost_flex: 1e-7,
    cache_read_input_token_cost_priority: 4e-7,
    input_cost_per_token: 0.000002,
    input_cost_per_token_above_272k_tokens: 0.000004,
    input_cost_per_token_above_272k_tokens_flex: 0.000002,
    input_cost_per_token_batches: 0.000001,
    input_cost_per_token_flex: 0.000001,
    input_cost_per_token_priority: 0.000004,
    litellm_provider: 'openai',
    max_input_tokens: 1050000,
    max_output_tokens: 128000,
    max_tokens: 128000,
    mode: 'chat',
    output_cost_per_token: 0.000012,
    output_cost_per_token_above_272k_tokens: 0.000018,
    output_cost_per_token_above_272k_tokens_flex: 0.000009,
    output_cost_per_token_batches: 0.000006,
    output_cost_per_token_flex: 0.000006,
    output_cost_per_token_priority: 0.000024,
    regional_processing_uplift_multiplier_eu: 1.1,
    regional_processing_uplift_multiplier_us: 1.1,
    search_context_cost_per_query: {
      search_context_size_high: 0.01,
      search_context_size_low: 0.01,
      search_context_size_medium: 0.01,
    },
    supported_endpoints: ['/v1/chat/completions', '/v1/batch', '/v1/responses'],
    supported_modalities: ['text', 'image'],
    supported_output_modalities: ['text'],
    supports_function_calling: true,
    supports_minimal_reasoning_effort: false,
    supports_native_streaming: true,
    supports_none_reasoning_effort: true,
    supports_parallel_function_calling: true,
    supports_pdf_input: true,
    supports_prompt_caching: true,
    supports_reasoning: true,
    supports_response_schema: true,
    supports_system_messages: true,
    supports_tool_choice: true,
    supports_vision: true,
    supports_web_search: true,
    supports_xhigh_reasoning_effort: true,
    cache_read_input_token_cost_above_272k_tokens_priority: 8e-7,
    input_cost_per_token_above_272k_tokens_priority: 0.000008,
    output_cost_per_token_above_272k_tokens_priority: 0.000036,
    supports_service_tier: true,
  },
  'gpt-5.6-luna': {
    cache_creation_input_token_cost: 2.5e-7,
    cache_creation_input_token_cost_above_272k_tokens: 5e-7,
    cache_creation_input_token_cost_above_272k_tokens_flex: 2.5e-7,
    cache_creation_input_token_cost_flex: 1.25e-7,
    cache_creation_input_token_cost_priority: 5e-7,
    cache_read_input_token_cost: 2e-8,
    cache_read_input_token_cost_above_272k_tokens: 4e-8,
    cache_read_input_token_cost_above_272k_tokens_flex: 2e-8,
    cache_read_input_token_cost_flex: 1e-8,
    cache_read_input_token_cost_priority: 4e-8,
    input_cost_per_token: 2e-7,
    input_cost_per_token_above_272k_tokens: 4e-7,
    input_cost_per_token_above_272k_tokens_flex: 2e-7,
    input_cost_per_token_batches: 1e-7,
    input_cost_per_token_flex: 1e-7,
    input_cost_per_token_priority: 4e-7,
    litellm_provider: 'openai',
    max_input_tokens: 1050000,
    max_output_tokens: 128000,
    max_tokens: 128000,
    mode: 'chat',
    output_cost_per_token: 0.0000012,
    output_cost_per_token_above_272k_tokens: 0.0000018,
    output_cost_per_token_above_272k_tokens_flex: 9e-7,
    output_cost_per_token_batches: 6e-7,
    output_cost_per_token_flex: 6e-7,
    output_cost_per_token_priority: 0.0000024,
    regional_processing_uplift_multiplier_eu: 1.1,
    regional_processing_uplift_multiplier_us: 1.1,
    search_context_cost_per_query: {
      search_context_size_high: 0.01,
      search_context_size_low: 0.01,
      search_context_size_medium: 0.01,
    },
    supported_endpoints: ['/v1/chat/completions', '/v1/batch', '/v1/responses'],
    supported_modalities: ['text', 'image'],
    supported_output_modalities: ['text'],
    supports_function_calling: true,
    supports_minimal_reasoning_effort: false,
    supports_native_streaming: true,
    supports_none_reasoning_effort: true,
    supports_parallel_function_calling: true,
    supports_pdf_input: true,
    supports_prompt_caching: true,
    supports_reasoning: true,
    supports_response_schema: true,
    supports_system_messages: true,
    supports_tool_choice: true,
    supports_vision: true,
    supports_web_search: true,
    supports_xhigh_reasoning_effort: true,
    cache_read_input_token_cost_above_272k_tokens_priority: 8e-8,
    input_cost_per_token_above_272k_tokens_priority: 8e-7,
    output_cost_per_token_above_272k_tokens_priority: 0.0000036,
    supports_service_tier: true,
  },
}

// GPT-6 Astra 暂按 gpt-5.6-sol 同价兜底（官方未单独公开价时）
// DEC_20260905_194420 Astra 完整支持；价源补齐后可删本别名
GPT56_SERIES_FALLBACK_PRICING['gpt-6-astra'] = GPT56_SERIES_FALLBACK_PRICING['gpt-5.6-sol']
GPT56_SERIES_FALLBACK_PRICING['gpt-6'] = GPT56_SERIES_FALLBACK_PRICING['gpt-5.6-sol']
