/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Account_selector: typeof import('./src/components/common/account_selector.vue')['default']
    Action_dropdown: typeof import('./src/components/common/action_dropdown.vue')['default']
    App_date_range_picker: typeof import('./src/components/common/app_date_range_picker.vue')['default']
    App_dialog: typeof import('./src/components/common/app_dialog.vue')['default']
    App_input: typeof import('./src/components/common/app_input.vue')['default']
    App_pagination: typeof import('./src/components/common/app_pagination.vue')['default']
    App_switch: typeof import('./src/components/common/app_switch.vue')['default']
    App_tooltip: typeof import('./src/components/common/app_tooltip.vue')['default']
    Confirm_modal: typeof import('./src/components/common/confirm_modal.vue')['default']
    Custom_dropdown: typeof import('./src/components/common/custom_dropdown.vue')['default']
    CustomDropdown: typeof import('@/components/common/custom_dropdown.vue')['default']
    Cute_option_cards: typeof import('./src/components/common/cute_option_cards.vue')['default']
    Dialog_side_nav: typeof import('./src/components/common/dialog_side_nav.vue')['default']
    Logo_title: typeof import('./src/components/common/logo_title.vue')['default']
    Modal_transition: typeof import('./src/components/common/modal_transition.vue')['default']
    Model_picker: typeof import('./src/components/common/model_picker.vue')['default']
    Model_selector: typeof import('./src/components/common/model_selector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Segmented_tabs: typeof import('./src/components/common/segmented_tabs.vue')['default']
    Stat_card: typeof import('./src/components/common/stat_card.vue')['default']
    Theme_toggle: typeof import('./src/components/common/theme_toggle.vue')['default']
    Toast_notification: typeof import('./src/components/common/toast_notification.vue')['default']
    Unified_test_modal: typeof import('./src/components/common/unified_test_modal.vue')['default']
  }
}
